[package]
name = "mush"
version = "0.1.0"
description = "Docker-based application deployment tool for developer"
license = "MIT"
edition = "2022"

[legacy-fetch]
getoptions = "https://github.com/ko1nksm/getoptions/releases/download/v3.3.0/getoptions"
gengetoptions = "https://github.com/ko1nksm/getoptions/releases/download/v3.3.0/gengetoptions"

[legacy-build]
lib-getoptions = "gengetoptions library > getoptions.sh"